service: serverless-flask

package:
  exclude:
    - "site/**"

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  messageTableName: 'message-table-${self:provider.stage}'
  channelTableName: 'channel-table-${self:provider.stage}'
  wsgi:
    app: notify_run_server.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["MessageTable", "Arn" ] }
        - { "Fn::GetAtt": ["ChannelTable", "Arn" ] }
  environment:
    NOTIFY_DB_URL: "dynamodb:${self:custom.messageTableName}:${self:custom.channelTableName}"
    NOTIFY_VAPID_PRIVKEY: ${env:NOTIFY_VAPID_PRIVKEY}
    NOTIFY_VAPID_PUBKEY: ${env:NOTIFY_VAPID_PUBKEY}
    NOTIFY_VAPID_EMAIL: ${env:NOTIFY_VAPID_EMAIL}
    NOTIFY_API_SERVER: ${env:NOTIFY_API_SERVER}
    NOTIFY_WEB_SERVER: ${env:NOTIFY_WEB_SERVER}


functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    ChannelTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: channelId
            AttributeType: S
        KeySchema:
          -
            AttributeName: channelId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.channelTableName}

    MessageTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: channelId
            AttributeType: S
          -
            AttributeName: messageTime
            AttributeType: S
        KeySchema:
          -
            AttributeName: channelId
            KeyType: HASH
          -
            AttributeName: messageTime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.messageTableName}
